### PR TITLE
Introduce a decorator for handling expected units

### PR DESCRIPTION
**Pull request by WillJRoper**
This PR introduces an `accepts` decorator. This decorator is modelled after `unyt.accepts` but introduces some Synthesizer specific functionality.

When using `accepts` you can define the units expected for an argument. The decorator will then first check units have been passed for that argument, if so it will perform a conversion to the expected unit (if not already in the that unit). 

This reduces boilerplate where we already check that units have been passed, perform conversions, and check units are compatible, and will also improve safety if employed across the codebase. 

There is no obvious performance penalty to this since we were already performing the wrapped checks in many places.

One limitation I've already spotted is arguments that are tuples/lists of unyt_quantities can't currently be handled in its current form. Should they be? I can envision some ways to make it work but it will introduce lots of `if isinstance` logic.

## Issue Type

- Enhancement

## Checklist
- [x] I have read the [CONTRIBUTING.md]() -->
- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by stephenmwilkins** [comment]
Can you point to a specific example of taking a tuple of values? Can these be changed to split into individual arguments or arrays?

**Comment by WillJRoper** [comment]
For instance, `window` [here](https://github.com/flaresimulations/synthesizer/blob/main/src/synthesizer/sed.py#L530) but it's far from the only example. I could make it work by passing a tuple to `accepts` which would mean it knows how to interpret it. 

Splitting it out into separate arguments would work in that example but then you're tying yourself to not having tuples. Arrays could work but then you have mutable arguments for something that should immutable and that feels icky.

**Comment by WillJRoper** [comment]
Tuples and list arguments are now handled properly.

**Review by christopherlovell — APPROVED** [review]
Looks good, haven't checked every doc or example explicitly but all tests are passing

**Pull request merged**
