### PR TITLE
Save initial mass in particle/stars.py as numpy array

### PR DESCRIPTION
**Pull request by louiseseeyave**
Save initial stellar masses in particle/stars.py as numpy array in order to avoid masking error down the line.

## Issue Type

- Bug
- Enhancement

## Checklist

- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by christopherlovell** [comment]
I don't understand why the task checker is failing for some people. Need to investigate

**Review by WillJRoper — CHANGES_REQUESTED** [review]
CAn you elaborate on why this is neceesary? As far as I am aware `np.array()` doesn't reliably make a copy of the data and the `initial_masses` should normally be a numpy array prior to this? In fact, they should really have units attached to them and be a `unyt_array`.

**Comment by louiseseeyave** [comment]
Ahh that's fair. I'd input the initial masses as a list, didn't realise it should have been a numpy / unyt array - so I was getting an error when this list was masked later on. Shall I close this pull request?

**Comment by WillJRoper** [comment]
Or maybe close this one and raise new one since the task checker appears borked

**Comment by louiseseeyave** [comment]
I'll reopen another PR as the checks are failing.

**Pull request closed without merging**
