### PR TITLE
added test_grid

### PR DESCRIPTION
**Pull request by stephenmwilkins**
## Issue Type

- [ ] Bug
- [x] Document
- [ ] Enhancement

## Checklist

- [] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by stephenmwilkins** [comment]
I've now updated the grid and parametric examples to use the test-grid.

**Comment by stephenmwilkins** [comment]
In hindsight I should have extended the test grid to 2um, not just 1um.

**Comment by stephenmwilkins** [comment]
I also moved more complex examples to `examples/misc` for now.

**Comment by christopherlovell** [comment]
Can you raise an issue about extending the test grid to 2um, someone can tackle at a later date

**Review by christopherlovell — APPROVED** [review]

**Pull request merged**
