### PR TITLE
Particle dev

### PR DESCRIPTION
**Pull request by stephenmwilkins**
- Updates to IGM module and example
- Re-writing of particle/galaxy module including provision of dust methods (screen, CF00, los).
- Addition of example of creating a particle SED including dust.

### CODE REVIEW

**Comment by christopherlovell** [comment]
`synthesizer/weights.c` is a temporary file generated by cython and shouldn't be included in the repo

**Comment by christopherlovell** [comment]
If you merge the other branches into this one, we can integration test in a single PR

**Comment by stephenmwilkins** [comment]
Honestly that would be a severe pain since I branched from two different points. I promise I'll fix it and do it properly next time.

**Comment by christopherlovell** [comment]
I've managed to merge them in, can you check everything looks okay? One thing I left in was `synthesizer/particle/particles.py` as I wasn't sure if this should have been deleted in the imaging branch.

You should now be able to fix the masses (initial / current) and other breaking changes in this branch

**Comment by stephenmwilkins** [comment]
It appears to work now!

**Review by christopherlovell — CHANGES_REQUESTED** [review]
integration test done, needs to be run through flake8

**Review by christopherlovell — APPROVED** [review]

**Pull request merged**
