### PR TITLE
Fixed powers and whitespace in spectra labels

### PR DESCRIPTION
**Pull request by WillJRoper**
DWISOTT: automatic parsing of `unyt` units into an axis label was missing whitespace and a handler for powers.

## Issue Type

- Bug

## Checklist
- [x] I have read the [CONTRIBUTING.md]() -->
- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by stephenmwilkins** [comment]
Ideally we'd use the `latex_representation` of the units right? Is the issue that is forces things to be fractions instead of using powers?

**Comment by WillJRoper** [comment]
This does use the latex representation. The issue was the conversion from `unyt` string to latex was ignoring the spaces in math mode and I had blindly removed multiplication before handling powers.

**Comment by stephenmwilkins** [comment]
But e.g. `str(plt_spectra.units)` doesn't produce the latex representation right?

**Comment by WillJRoper** [comment]
No, that's what the replacing does?

**Comment by stephenmwilkins** [comment]
But why not using the `latex_representation` property built into `unyt`? 

```
>>> from unyt import erg, s, Hz, cm
>>> fnu = 1 * erg/s/Hz/cm**2
>>> print(fnu.units)
erg/(Hz*cm**2*s)
>>> print(fnu.units.latex_repr)
\frac{\rm{erg}}{\rm{Hz} \cdot \rm{cm}^{2} \cdot \rm{s}}
```

The undesirable aspect of this is that uses \frac.

**Comment by WillJRoper** [comment]
😂 because I literally just learnt it exists! I'm now torn... I'd rather not use frac but my current implementation isn't very cleaver.

**Comment by WillJRoper** [comment]
Yea, bear with me. I can achieve it with regex. Commit incoming.

**Comment by WillJRoper** [comment]
Done. It now uses Latex representation and swaps `frac` for `\`.

**Review by stephenmwilkins — APPROVED** [review]

**Pull request merged**
