### PR TITLE
Added Image and survey functionality

### PR DESCRIPTION
**Pull request by WillJRoper**
Added the ability to add images together. 

Because of the complications with different types of image objects, this enables a number of different possibilities, all are demonstrated in examples/image/image_addition.py. 

Also added the ability to compare FilterCollections via == and !=.

This PR also handles an edge case where `import urllib` can produce `AttributeError` (in filters.py).

## Issue Type

- [ ] Bug
- [ ] Document
- [x] Enhancement

## Checklist

- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by stephenmwilkins** [comment]
Failing checks!

**Comment by WillJRoper** [comment]
I'm a fool and accidentally continued editing the branch for this PR before it was merged. I'll draft this for now and ammend it with all the functionality that has been added when finished.

**Comment by WillJRoper** [comment]
Right, this PR should be ready. It's got a lot of small things in it:

- Better handling of filter transmission curve convolution. 
- The functionality to do Surveys (NOTE: this is purely documented but other functionality in this branch is needed elsewhere. I'll fix this all up when I have time but really need to do other work). 
- Image addition. 
- PSFed images.
- noisy images.
- Ran black on the whole repo.

**Review by stephenmwilkins — APPROVED** [review]
I haven't checked everything but most of that is Black (I hope). I've looked at the new Image/Scene stuff. Let's press GO and hope for the best ;)

**Pull request merged**
