### PR TITLE
Grid tidy up

### PR DESCRIPTION
**Pull request by stephenmwilkins**
## Issue Type

Have tidied up the Grid class including renaming a few things and improving the docs.

- renamed and harmonised various `Grid` methods, particularly those for accessing lines and spectra directly from the grid by providing a grid-point e.g. `get_lines_info` -> `get_lines`.
- this was made possible by moving the methods that read in spectra and lines from the HDF5 file into the `__init__()` as I couldn't see a justification for not reading them straight in.
- renamed various attributes, again for harmonisation purposes, e.g. `available_spectra` and `available_spectra` now exist. 
- similarly when calling `get_spectra` or `get_line` we now provide `spectra_id` or `line_id`.
- added various exceptions, e.g. if `spectra_id` is not in `available_spectra`.
- some additional commenting and improvement of the doc strings.
- updated all docs and examples.

## Checklist

- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by christopherlovell — COMMENTED** [review]
Can you detail what changes to methods are actually implemented here, i.e. what methods are removed, what methods are updated?

**Comment by WillJRoper** [comment]
> Can you detail what changes to methods are actually implemented here, i.e. what methods are removed, what methods are updated?

+1

**Comment by WillJRoper** [comment]
@stephenmwilkins Note my last 2 commits. We should move to absolute imports for clarity. Please capitalise comments and only use doc strings for doc strings! To split a string over multiple lines you can simply end the string and start a new one on a new line.

**Comment by stephenmwilkins** [comment]
> Can you detail what changes to methods are actually implemented here, i.e. what methods are removed, what methods are updated?

Done above.

**Review by WillJRoper — APPROVED** [review]

**Pull request merged**
