### PR TITLE
Generate blackhole grids

### PR DESCRIPTION
**Pull request by stephenmwilkins**
## Issue Type

- [ ] Bug
- [ ] Document
- [ ] Enhancement

## Checklist

- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by stephenmwilkins** [comment]
I have re-written the blackhole grid generation code and have generated two blackhole grids.

One of these is a 1D grid (log10T) and I've copied it over to the `test_grid` dir since it's small (<2MB). 

I will have 2D grids made soon (log10T, log10Z) and can make higher-dimensionality grids with just lines.

I've added a notebook on blackholes grids, but this might be better put somewhere else eventually.

**Review by WillJRoper — CHANGES_REQUESTED** [review]
Looks good code wise but the doc strings are not in the googledoc format. See the contributing guidelines. There is also a mixture of docstring styles, neither of which are the one used in Synthesizer.

**Comment by WillJRoper** [comment]
A merge of main is also required.

**Comment by stephenmwilkins** [comment]
When did we even change the doc string format? I actually preferred the one with the underscores. Updated though.

**Comment by WillJRoper** [comment]
> When did we even change the doc string format? I actually preferred the one with the underscores. Updated though.

A long time ago with lots of discussion surrounding the choice. The google doc one is a bit more succinct with less repetition in class structures.

**Comment by stephenmwilkins** [comment]
@WillJRoper `blackholes.ipynb` won't run for me but I don't think that's due to any changes I've made; however, I did remove the grid specific elements.

**Comment by WillJRoper** [comment]
Check `_coordinates` and `_velocities` are in `__slots__` on the BlackHoles class.

**Comment by WillJRoper** [comment]
Have you merged the latest version of main?

**Comment by stephenmwilkins** [comment]
Ah... classic, I hadn't pulled main before trying to merge.

**Review by WillJRoper — APPROVED** [review]

**Pull request merged**
