### PR TITLE
added functionality to add together two parametric galaxies

### PR DESCRIPTION
**Pull request by stephenmwilkins**
## Issue Type

- [ ] Bug
- [ ] Document
- [x] Enhancement

## Checklist

- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Added functionality to allow two galaxies to be added together. At the moment this only applies to the SEDs and SFZHs contained within the galaxies as lines and images do not yet have this functionality.

Also added a __str__ method to summarise the galaxies and the lines/spectra/images the galaxy contains.

### CODE REVIEW

**Review by WillJRoper — CHANGES_REQUESTED** [review]
Looks great! But can you use Numpydoc doc string format: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html 

There are too few comments in general, and do PEP-8 compliant commenting: no dashes, a capital letter at the start of the comment unless it's inline.

**Comment by WillJRoper** [comment]
https://peps.python.org/pep-0008/#comments 
Seems I'm wrong about the lower case in inline comments 🤔 but the rest I stand by 😅

**Comment by stephenmwilkins** [comment]
Improved the doc string for these changes. Will improve the rest of the module in a later PR.

**Review by christopherlovell — APPROVED** [review]
Can wait for docs to be updated, or merge now

**Comment by stephenmwilkins** [comment]
Merge now and I'll improve the other docs later.

**Review by WillJRoper — APPROVED** [review]

**Pull request merged**
