### PR TITLE
Enabling per particle escape fractions

### LINKED ISSUE #124: fesc could be an array.
Should we assume this as standard and simply make an fesc array if a single value is passed? My vote is yes. Its a small temporary memory footprint increase.

### PR DESCRIPTION
**Pull request by WillJRoper**
Although not a common use case it would be nice to be able to give star particles particle specific escape fractions (i.e. based on age or metallicity). This PR enables this as a possibility.

- `fesc` can be a single value. If it is an array full of that value is made to pass to the C extension. This is short lived enough and only 32 bit so has a minimal effect on footprint.
- `fesc` can also be passed as any array.
- Since the integrated spectra extension limits lam loops by calculating the weight grid first and then applying it to spectra the escape fraction is combined into the weights, this is all hidden in the backend but this approach is the only way to maintain this optimisation and enable the `fesc` array. It works but is worth noting.
- Closes #124 

## Issue Type

- Enhancement

## Checklist
- [x] I have read the [CONTRIBUTING.md]() -->
- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aswinpvijayan** [comment]
Looks good.
Can anyone check again if this line is correct: https://github.com/flaresimulations/synthesizer/blob/ab4e2b1a0d1f7b48d3a6103c3e1d2ee6dfcdb2a6/src/synthesizer/particle/stars.py#L755
Shouldn't the nebular continuum be corrected for fesc? @stephenmwilkins

**Comment by stephenmwilkins** [comment]
> Looks good. Can anyone check again if this line is correct:
> 
> https://github.com/flaresimulations/synthesizer/blob/ab4e2b1a0d1f7b48d3a6103c3e1d2ee6dfcdb2a6/src/synthesizer/particle/stars.py#L755
> 
> 
> Shouldn't the nebular continuum be corrected for fesc? @stephenmwilkins

Short answer is no, long answer is explained by the bit commented out after the line. `continuum` should be the sum of `nebular_continuum` (which should have an (`1-fesc`) factor and  `stellar_continuum` that won't. Since `stellar_continuum` is generally >> `nebular_continuum` it would normally be fine. But we should do it properly and use both separate continuum elements. Not sure why we didn't in the first place.

**Comment by WillJRoper** [comment]
@aswinpvijayan can you make an issue for this outside this PR?

**Comment by stephenmwilkins** [comment]
> > Looks good. Can anyone check again if this line is correct:
> > https://github.com/flaresimulations/synthesizer/blob/ab4e2b1a0d1f7b48d3a6103c3e1d2ee6dfcdb2a6/src/synthesizer/particle/stars.py#L755
> > 
> > Shouldn't the nebular continuum be corrected for fesc? @stephenmwilkins
> 
> Short answer is no, long answer is explained by the bit commented out after the line. `continuum` should be the sum of `nebular_continuum` (which should have an (`1-fesc`) factor and `stellar_continuum` that won't. Since `stellar_continuum` is generally >> `nebular_continuum` it would normally be fine. But we should do it properly and use both separate continuum elements. Not sure why we didn't in the first place.

Actually, this should be `incident_continuum` not `stellar_continuum`. I can't remember if these are actually recorded in the grids separately though.

**Review by stephenmwilkins — APPROVED** [review]
I'm going to assume you've done all the c stuff correctly.

**Pull request merged**
