### PR TITLE
Add a method to calculate integrated spectra for all the available particle_spectra

### PR DESCRIPTION
**Pull request by stephenmwilkins**
Adds a method to calculate integrated spectra for all the available particle_spectra.

## Issue Type

- Bug
- Document
- Enhancement

## Checklist
- [ ] I have read the [CONTRIBUTING.md]() -->
- [ ] I have added docstrings to all methods
- [ ] I have added sufficient comments to all lines
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no pep8 errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by WillJRoper** [comment]
This already exists: https://github.com/flaresimulations/synthesizer/blob/main/src/synthesizer/particle/galaxy.py#L423C1-L449C17

Please check.

**Comment by WillJRoper** [comment]
If you wanted to include this on a component you could take the loop from that method and move it to the `Particles` base class and then wrap that in the method above.

**Comment by stephenmwilkins** [comment]
Ah... so it does, I was only looking on the component. I think it's useful on component but maybe not essential.

**Comment by WillJRoper** [comment]
Superseded by #635

**Pull request closed without merging**
