### PR TITLE
Plot keywords in component plot method

### PR DESCRIPTION
**Pull request by christopherlovell**
added a `kwargs` argument to the stellar component `plot_spectra` method that is passed to the sed `plot_spectra` method, to provide more control.

- also fixed a small typo in sed.py

## Issue Type
- Enhancement

## Checklist
- [x] I have read the [CONTRIBUTING.md]()
- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [] I have made corresponding changes to the documentation
- [] My changes generate no pep8 errors
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by WillJRoper** [comment]
Should the `kwargs` also not then be passed to the `plot` call?

**Comment by christopherlovell** [comment]
They are?

**Comment by WillJRoper** [comment]
https://github.com/flaresimulations/synthesizer/blob/5bce857f5b6ef2150bd1be3ff1610be4c8a76c08/src/synthesizer/sed.py#L1194 
Are they?

**Comment by christopherlovell** [comment]
You've misunderstood. These are kwargs passed _to_ the sed method from the stellar component method

**Comment by christopherlovell** [comment]
Oh I understand your first comment now. I didn't write this with this in mind, just linking these methods

**Comment by WillJRoper** [comment]
My bad, I totally misunderstood the reasoning 😅 sorry!

**Comment by WillJRoper** [comment]
It would be nice to pass kwargs to the plot HOWEVER that's very messy if mixed with kwargs for other uses. Lets ignore it! For that fine level of control a user should really be making their own plot.

**Review by WillJRoper — APPROVED** [review]

**Pull request merged**
