### PR TITLE
added parametric morphology and some bug fixes

### PR DESCRIPTION
**Pull request by stephenmwilkins**
## Issue Type

- [ ] Bug
- [ ] Document
- [ ] Enhancement

## Checklist

- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by WillJRoper — CHANGES_REQUESTED** [review]
`morphology.img` should be part of `ParametricImage` not the morphology class, I can modify this though. 

I also would remove the image creation with the morphology object from the initialisation of the image. Note that allowing `morphology=None` as the default argument means initialisation will fail if it is not provided. It should either be required or not done at initialisation. Also, `filters` is a required argument, are you always going to have a filter with a parametric model?

**Comment by WillJRoper** [comment]
Also, you ticked that you have modified the docs which I'm pretty sure is a lie 😂 don't just tick boxes to dodge the check failing 😂

**Comment by stephenmwilkins** [comment]
> `morphology.img` should be part of `ParametricImage` not the morphology class, I can modify this though.
> 
> I also would remove the image creation with the morphology object from the initialisation of the image. Note that allowing `morphology=None` as the default argument means initialisation will fail if it is not provided. It should either be required or not done at initialisation. Also, `filters` is a required argument, are you always going to have a filter with a parametric model?

The reason for morphology.img being there was because I could imagine a morphology function that didn't provide method to call with xx, yy. For example if you wanted a collection of point sources.

**Review by WillJRoper — APPROVED** [review]

**Comment by WillJRoper** [comment]
I approved it but the linter caught some issues (similar to my filters.py issues 😅). Rectify those and it'll merge.

**Comment by WillJRoper** [comment]
Still not sure why Morphology needs to have `.img` but I will take a look and see if I can relocate it to allow for that functionality. It really shouldn't have imaging functionality. That should be with the images.

**Comment by stephenmwilkins** [comment]
> Still not sure why Morphology needs to have `.img` but I will take a look and see if I can relocate it to allow for that functionality. It really shouldn't have imaging functionality. That should be with the images.

I can understand that but I think it's neater to include all the different morphological models in one code. Like I said, some morphological models can't be described by a function that you pass xx, yy to.

**Pull request merged**
