### PR TITLE
Second attempt at image updates.

### PR DESCRIPTION
**Pull request by WillJRoper**
This contains the imaging and survey updates and no extras. It includes:

- Better handling of filter application.
- Survey functionality for both imaging and photometry.
- Applying a PSF to an image.
- Applying noise to an image.
- Image addition.
- Image resampling.
- Examples covering these operations.

## Issue Type

- [n.a] Bug
- [n.a] Document
- [x] Enhancement

## Checklist

- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by WillJRoper** [comment]
Argh one obvious issue is the camels plots have changed on the y axis!? I ran both @christopherlovell and my version of that example and the plots were identical (i.e. both different).

**Comment by WillJRoper** [comment]
In fact I get the same answer on main 🙃

**Comment by stephenmwilkins** [comment]
Conflicts and failing checks!

**Comment by WillJRoper** [comment]
Conflict resolved. The failing check is just the Docs which no one is updating but I'm actually being honest about it 😂. We need to have a dedicated effort to update the docs soon.

**Comment by stephenmwilkins** [comment]
In terms of dedicated docs I think it only makes sense once things have settled down. I hope we can do this soon once we have the basic spectroscopy/photometry generation sorted.

**Review by christopherlovell — APPROVED** [review]

**Pull request merged**
